apiVersion: batch/v1
kind: Job
metadata:
  name: mysql-migration
spec:
  template:
    metadata:
      labels:
        app: mysql-migration
        tier: backend
    spec:
      containers:
        - name: mysql-migration
          image: mysql-migration:latest
          imagePullPolicy: Never
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: client-secret
                  key: MYSQL_ROOT

            - name: MYSQL_DATABASE
              value: GiftcardSiteDB

          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-volume-mount
              mountPath: /var/lib/mysql

      volumes:
        - name: mysql-volume-mount
          persistentVolumeClaim:
            claimName: mysql-pvc


      restartPolicy: Never
